### ISSUE TITLE
Library currently broken

### ISSUE THREAD

**Issue by andre2007** [nin-jin/go.d#2]
Thanks for this great library. Is there a chance you can solve the open issues to get the library working again?

- Replace dependency `vibe-d:core` with `vibe-core`
- Also dependency `dests` itself is broken. Maybe the assertions could be replaced with d `assert` statements

There are also new posts on your topic https://forum.dlang.org/post/mailman.3233.1589729155.31109.digitalmars-d@puremagic.com

**Comment by nin-jin** [comment]
I'm going to fix it at weekend.

**Comment by andre2007** [comment]
Issues in dub package `dests` are solved: https://github.com/dexset/dests/issues/3

**Comment by nin-jin** [comment]
I have updated the code. But it isn't ready to use currently because:

1. I rewrote code to use std.parallelism instead of vibe.d. So, it's difficult to integrate fibers with tasks. It would be cool if someone help me with it. There are docstrings, tests and diagrams.

2. Race condition. I'm going to closely review algorithm.

**Comment by andre2007** [comment]
Thanks for your work. When it is in a usable state I would like to ask Ali Çehreli to add a chapter in his book. This library is great and hidden so deeply, you can just find it by chance.

May I ask you to add an issue here, describing what needs to be done in detail? https://github.com/dlang/projects/issues
This list of issues is considered for gsoc / autumn of code projects.
Thanks.

**Comment by nin-jin** [comment]
I have fixed all issues. But I had to return vibe-core dependency.

**Comment by nin-jin** [comment]
Added project: https://github.com/dlang/projects/issues/65
Tell me if I can help more to promote this project :-)

**Comment by mw66** [comment]
I saw you make a new release 2.0, but dub is not picking it up:

https://code.dlang.org/packages/jin-go

it still shows 1.0.5 released 4 years ago

Maybe you want to have a check, or ask the dub team for help: 

https://github.com/dlang/dub-registry/issues

**Comment by nin-jin** [comment]
I have manually triggered update.

**Comment by andre2007** [comment]
Thanks a lot. There is the dlang tour which lists some specific dub packages, like https://tour.dlang.org/tour/en/dub/mir-algorithm
It would be great to have it here.

Did you also thought about moving your dub package to the dlang-community organization? Your dub package is quite important for the dlang community and having it there makes it more easy to reference it.
More info here https://github.com/dlang-community/discussions

**Comment by nin-jin** [comment]
I have opened an issue: https://github.com/dlang-community/discussions/issues/45

**Comment by nin-jin** [comment]
I think go.d isn't ready to publish in tour because:
- required at least one review.
- required at least one production usage.

It's required for api/implementation stabilization.

**Comment by mw66** [comment]
or: beat Go by performance :-)

Right now it's still 2~4x time slower than Go.

**Comment by nin-jin** [comment]
VibeD dependency elimination is required for that. I tried, but defeat to use std.concurrency directly.
